#!/bin/bash

#SBATCH -J mm4096_jik                # Job name
#SBATCH -o matrix4096_jik/mm4096_jik.out%j            # Name of stdout output file
#SBATCH -e matrix4096_jik/mm4096_jik.err%j            # Name of stderr error file
#SBATCH -p skx-normal                  # Queue (partition) name
#SBATCH -N 1                    # Total # of nodes (must be 1 for serial)
#SBATCH -n 1                    # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 1:30:00              # Run time (hh:mm:ss)

#SBATCH --mail-type=all
#SBATCH --mail-user=sangram.kate@utexas.edu

python run_perf_loop.py &

wait

